export const INCREMENTVALUE = "INCREMENTVALUE"
export const SONGSVALUE = "SONGSVALUE"
export const BOTTOUMPLAY = "BOTTOUMPLAY"
export const INTREVAL = "INTREVAL"
export const ISPLAYING = "ISPLAYING"
export const DURATION = "DURATION"
export const THUMBNAIL = "THUMBNAIL"
export const ADDFAVORITE = "ADDFAVORITE"
export const REMOVEFAVORITE = "REMOVEFAVORITE"
export const RESTOREFAVORITE = "RESTOREFAVORITE"




